version: "3.7"
services:
  output:
    # configuration for output
    image: scalalocicontainerize/thesis:thesis_samples_eval_msa_output
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_samples_eval_msa_output
        target: /data
    networks:
      pipeline:
        aliases:
          - thesis_samples_eval_msa_output
      thesis_samples_eval_msa_pipeline:
        aliases:
          - thesis_samples_eval_msa_output
    labels:
      com.loci.containerize.module: "thesis.samples.eval.msa.Pipeline"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_samples_eval_msa_output
----------------
  SERVICE API
----------------
thesis_samples_eval_msa_output provides the following to services:
 -

thesis_samples_eval_msa_output requires the following services:
@TCP	:8164		[ thesis.samples.eval.msa.Pipeline.Hasher ]

"
  archiver:
    # configuration for archiver
    image: scalalocicontainerize/thesis:thesis_samples_eval_msa_archiver
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_samples_eval_msa_archiver
        target: /data
    networks:
      pipeline:
        aliases:
          - thesis_samples_eval_msa_archiver
      thesis_samples_eval_msa_pipeline:
        aliases:
          - thesis_samples_eval_msa_archiver
      thesis_samples_eval_msa_archiver:
  archiver_localdb:
    # configuration for the local database of archiver
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      thesis_samples_eval_msa_archiver:
        aliases:
          - thesis_samples_eval_msa_archiver_localdb
    volumes:
      - type: volume
        source: thesis_samples_eval_msa_archiver_localdb
        target: /data/db
    labels:
      com.loci.containerize.module: "thesis.samples.eval.msa.Pipeline"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_samples_eval_msa_archiver
----------------
  SERVICE API
----------------
thesis_samples_eval_msa_archiver provides the following to services:
@TCP	:8161		[ thesis.samples.eval.msa.Pipeline.Hasher ]
@TCP	:8162		[ thesis.samples.eval.msa.Pipeline.Input ]
@TCP	:8163		[ thesis.samples.eval.msa.Pipeline.Filter ]

thesis_samples_eval_msa_archiver requires the following services:
 -

"
  hasher:
    # configuration for hasher
    image: scalalocicontainerize/thesis:thesis_samples_eval_msa_hasher
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_samples_eval_msa_hasher
        target: /data
    networks:
      pipeline:
        aliases:
          - thesis_samples_eval_msa_hasher
      thesis_samples_eval_msa_pipeline:
        aliases:
          - thesis_samples_eval_msa_hasher
    labels:
      com.loci.containerize.module: "thesis.samples.eval.msa.Pipeline"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_samples_eval_msa_hasher
----------------
  SERVICE API
----------------
thesis_samples_eval_msa_hasher provides the following to services:
@TCP	:8164		[ thesis.samples.eval.msa.Pipeline.Output ]
@TCP	:8165		[ thesis.samples.eval.msa.Pipeline.Filter ]

thesis_samples_eval_msa_hasher requires the following services:
@TCP	:8165		[ thesis.samples.eval.msa.Pipeline.Filter ]
@TCP	:8161		[ thesis.samples.eval.msa.Pipeline.Archiver ]

"
  filter:
    # configuration for filter
    image: scalalocicontainerize/thesis:thesis_samples_eval_msa_filter
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_samples_eval_msa_filter
        target: /data
    networks:
      pipeline:
        aliases:
          - thesis_samples_eval_msa_filter
      thesis_samples_eval_msa_pipeline:
        aliases:
          - thesis_samples_eval_msa_filter
    labels:
      com.loci.containerize.module: "thesis.samples.eval.msa.Pipeline"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_samples_eval_msa_filter
----------------
  SERVICE API
----------------
thesis_samples_eval_msa_filter provides the following to services:
@TCP	:8166		[ thesis.samples.eval.msa.Pipeline.Tagger ]

thesis_samples_eval_msa_filter requires the following services:
@TCP	:8165		[ thesis.samples.eval.msa.Pipeline.Hasher ]
@TCP	:8163		[ thesis.samples.eval.msa.Pipeline.Archiver ]

"
  tagger:
    # configuration for tagger
    image: scalalocicontainerize/thesis:thesis_samples_eval_msa_tagger
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_samples_eval_msa_tagger
        target: /data
    networks:
      pipeline:
        aliases:
          - thesis_samples_eval_msa_tagger
      thesis_samples_eval_msa_pipeline:
        aliases:
          - thesis_samples_eval_msa_tagger
    labels:
      com.loci.containerize.module: "thesis.samples.eval.msa.Pipeline"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_samples_eval_msa_tagger
----------------
  SERVICE API
----------------
thesis_samples_eval_msa_tagger provides the following to services:
@TCP	:8162		[ thesis.samples.eval.msa.Pipeline.Input ]

thesis_samples_eval_msa_tagger requires the following services:
@TCP	:8166		[ thesis.samples.eval.msa.Pipeline.Filter ]

"
  input:
    # configuration for input
    image: scalalocicontainerize/thesis:thesis_samples_eval_msa_input
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_samples_eval_msa_input
        target: /data
    ports:
      - "8424:8424"
    networks:
      pipeline:
        aliases:
          - thesis_samples_eval_msa_input
      thesis_samples_eval_msa_pipeline:
        aliases:
          - thesis_samples_eval_msa_input
    labels:
      com.loci.containerize.module: "thesis.samples.eval.msa.Pipeline"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_samples_eval_msa_input
----------------
  SERVICE API
----------------
thesis_samples_eval_msa_input provides the following to services:
 -

thesis_samples_eval_msa_input requires the following services:
@TCP	:8162		[ thesis.samples.eval.msa.Pipeline.Tagger ]
@TCP	:8162		[ thesis.samples.eval.msa.Pipeline.Archiver ]

"
networks:
  pipeline:
    external: true
  thesis_samples_eval_msa_pipeline:
    driver: overlay
    attachable: true
    internal: false
    name: thesis_samples_eval_msa_pipeline
  thesis_samples_eval_msa_archiver:
    driver: overlay
    internal: true
    attachable: false
    name: thesis_samples_eval_msa_archiver
volumes:
  thesis_samples_eval_msa_output:
  thesis_samples_eval_msa_archiver:
  thesis_samples_eval_msa_hasher:
  thesis_samples_eval_msa_filter:
  thesis_samples_eval_msa_tagger:
  thesis_samples_eval_msa_input:
  thesis_samples_eval_msa_archiver_localdb:
