version: "3.7"
services:
  worker:
    # configuration for worker
    image: scalalocicontainerize/thesis:thesis_samples_worker_worker
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_samples_worker_worker
        target: /data
    networks:
      masterworker:
        aliases:
          - thesis_samples_worker_worker
      thesis_samples_worker_masterworker:
        aliases:
          - thesis_samples_worker_worker
    labels:
      com.loci.containerize.module: "thesis.samples.worker.MasterWorker"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_samples_worker_worker
----------------
  SERVICE API
----------------
thesis_samples_worker_worker provides the following to services:
 -

thesis_samples_worker_worker requires the following services:
@TCP	:8175		[ thesis.samples.worker.MasterWorker.Master ]

"
  master:
    # configuration for master
    image: scalalocicontainerize/thesis:thesis_samples_worker_master
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_samples_worker_master
        target: /data
    networks:
      masterworker:
        aliases:
          - thesis_samples_worker_master
      thesis_samples_worker_masterworker:
        aliases:
          - thesis_samples_worker_master
    labels:
      com.loci.containerize.module: "thesis.samples.worker.MasterWorker"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_samples_worker_master
----------------
  SERVICE API
----------------
thesis_samples_worker_master provides the following to services:
@TCP	:8175		[ thesis.samples.worker.MasterWorker.Worker ]

thesis_samples_worker_master requires the following services:
 -

"
networks:
  masterworker:
    external: true
  thesis_samples_worker_masterworker:
    driver: overlay
    attachable: true
    internal: false
    name: thesis_samples_worker_masterworker
volumes:
  thesis_samples_worker_worker:
  thesis_samples_worker_master:
