version: "3.7"
services:
  formatter:
    # configuration for formatter
    image: scalalocicontainerize/thesis:thesis_listings_apigateway_timeservice_formatter
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_listings_apigateway_timeservice_formatter
        target: /data
    networks:
      timeservice_gateway:
        aliases:
          - thesis_listings_apigateway_timeservice_formatter
      thesis_listings_apigateway_timeservice_multitierapi:
        aliases:
          - thesis_listings_apigateway_timeservice_formatter
    labels:
      com.loci.containerize.module: "thesis.listings.APIGateway.timeservice.MultitierApi"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_listings_apigateway_timeservice_formatter
----------------
  SERVICE API
----------------
thesis_listings_apigateway_timeservice_formatter provides the following to services:
@TCP	:8152		[ thesis.listings.APIGateway.timeservice.MultitierApi.Manipulator ]
@TCP	:8153		[ thesis.listings.APIGateway.gateway.api.ConsumerApi.Gateway ]

thesis_listings_apigateway_timeservice_formatter requires the following services:
@TCP	:8151		[ thesis.listings.APIGateway.timeservice.MultitierApi.Server ]
@TCP	:8152		[ thesis.listings.APIGateway.timeservice.MultitierApi.Manipulator ]
@TCP	:8153		[ thesis.listings.APIGateway.gateway.api.ConsumerApi.Gateway ]

"
  server:
    # configuration for server
    image: scalalocicontainerize/thesis:thesis_listings_apigateway_timeservice_server
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_listings_apigateway_timeservice_server
        target: /data
    networks:
      timeservice_gateway:
        aliases:
          - thesis_listings_apigateway_timeservice_server
      thesis_listings_apigateway_timeservice_multitierapi:
        aliases:
          - thesis_listings_apigateway_timeservice_server
    labels:
      com.loci.containerize.module: "thesis.listings.APIGateway.timeservice.MultitierApi"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_listings_apigateway_timeservice_server
----------------
  SERVICE API
----------------
thesis_listings_apigateway_timeservice_server provides the following to services:
@TCP	:8151		[ thesis.listings.APIGateway.timeservice.MultitierApi.Formatter ]

thesis_listings_apigateway_timeservice_server requires the following services:
 -

"
  manipulator:
    # configuration for manipulator
    image: scalalocicontainerize/thesis:thesis_listings_apigateway_timeservice_manipulator
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_listings_apigateway_timeservice_manipulator
        target: /data
    networks:
      timeservice_gateway:
        aliases:
          - thesis_listings_apigateway_timeservice_manipulator
      thesis_listings_apigateway_timeservice_multitierapi:
        aliases:
          - thesis_listings_apigateway_timeservice_manipulator
    labels:
      com.loci.containerize.module: "thesis.listings.APIGateway.timeservice.MultitierApi"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_listings_apigateway_timeservice_manipulator
----------------
  SERVICE API
----------------
thesis_listings_apigateway_timeservice_manipulator provides the following to services:
 -

thesis_listings_apigateway_timeservice_manipulator requires the following services:
@TCP	:8152		[ thesis.listings.APIGateway.timeservice.MultitierApi.Formatter ]

"
networks:
  timeservice_gateway:
    external: true
  thesis_listings_apigateway_timeservice_multitierapi:
    driver: overlay
    attachable: true
    internal: false
    name: thesis_listings_apigateway_timeservice_multitierapi
volumes:
  thesis_listings_apigateway_timeservice_formatter:
  thesis_listings_apigateway_timeservice_server:
  thesis_listings_apigateway_timeservice_manipulator:
