version: "3.7"
services:
  service:
    # configuration for service
    image: thesis_samples_timeservice_service
    stdin_open: false
    tty: false
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_samples_timeservice_service
        target: /data
    networks:
      timeservice:
        aliases:
          - thesis_samples_timeservice_service
      thesis_samples_timeservice_multitierapi:
        aliases:
          - thesis_samples_timeservice_service
      thesis_samples_timeservice_service:
  service_localdb:
    # configuration for the local database of service
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      thesis_samples_timeservice_service:
        aliases:
          - thesis_samples_timeservice_service_localdb
    volumes:
      - type: volume
        source: thesis_samples_timeservice_service_localdb
        target: /data/db
    labels:
      com.loci.containerize.module: "thesis.samples.timeservice.MultitierApi"
      com.loci.containerize.description: "No description available for this service."
      com.loci.containerize.api: "
Description for service: thesis_samples_timeservice_service
----------------
  SERVICE API
----------------
thesis_samples_timeservice_service provides the following to services:
@TCP	:8191		[ thesis.samples.timeservice.MultitierApi.Client ]

thesis_samples_timeservice_service requires the following services:
 -

"
  client:
    # configuration for client
    image: thesis_samples_timeservice_client
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: any
      rollback_config:
        order: start-first
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first
    volumes:
      - type: volume
        source: thesis_samples_timeservice_client
        target: /data
    networks:
      timeservice:
        aliases:
          - thesis_samples_timeservice_client
      thesis_samples_timeservice_multitierapi:
        aliases:
          - thesis_samples_timeservice_client
    labels:
      com.loci.containerize.module: "thesis.samples.timeservice.MultitierApi"
      com.loci.containerize.description: "-"
      com.loci.containerize.api: "
Description for service: thesis_samples_timeservice_client
----------------
  SERVICE API
----------------
thesis_samples_timeservice_client provides the following to services:
 -

thesis_samples_timeservice_client requires the following services:
@TCP	:8191		[ thesis.samples.timeservice.MultitierApi.Server ]

"
  globaldb:
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      thesis_samples_timeservice_multitierapi:
        aliases:
          - thesis_samples_timeservice_multitierapi_globaldb
    volumes:
      - type: volume
        source: thesis_samples_timeservice_multitierapi_globaldb
        target: /data/db
networks:
  timeservice:
    external: true
  thesis_samples_timeservice_multitierapi:
    driver: overlay
    attachable: true
    internal: false
    name: thesis_samples_timeservice_multitierapi
  thesis_samples_timeservice_service:
    driver: overlay
    internal: true
    attachable: false
    name: thesis_samples_timeservice_service
volumes:
  thesis_samples_timeservice_service:
  thesis_samples_timeservice_client:
  thesis_samples_timeservice_service_localdb:
  thesis_samples_timeservice_multitierapi_globaldb:
